#include"strglob.h"

/*! 
 * @fn char **copy_strglob(const HAND_GLOB *hand)
 *
 * @brief copy the strings generated by the glob pattern to an array of strings
 *
 * @param [in] hand the handle to a string glob data structure
 *
 * @see fputs_strglob
 */

char **copy_strglob(const HAND_GLOB *hand) {
  STR_GLOB *pugx = hand->glob;
  const size_t size = hand->size;

  assert(pugx);

  char ***const kstr = cons_glob2astras(pugx);
  int *const *crp = hand->carp;

  register int *const *restrict crpp = crp;

  while(crpp && *crpp)
    crpp++;

  const size_t acnt = (1 + crpp - crp) * size;

  char **strings = malloc(acnt * sizeof*strings);

  if(!strings)
    exit_verbose("malloc", __FILE__, __LINE__);

  if(kstr && crp) {
    for(register int c = 0;crp[c];++c) {
      const int *restrict ind = crp[c];

      /* if(*ind == -1)
        break;

      if(size == 1) {
        *strings = strdup(kstr[0][*ind]);

        if(!*strings)
          exit_verbose("strdup", __FILE__, __LINE__);
      }
      else */
        for(register int k = 0;k < size;++k, ++ind) {
          if(!kstr[k] || *ind == -1 || !kstr[k][*ind])
            break;

            strings[k] = strdup(kstr[k][*ind]);

            if(!strings[k])
              exit_verbose("strdup", __FILE__, __LINE__);
          }
    }

    strings[size] = NULL;
  }

  return strings;
}
