.\" strglob.1 - manual page for strglob
.\"
.\"
.TH STRGLOB 1 2018\-06\-05 "strglob 1.0.4"
.SH NAME
\fBstrglob\fR \- command-line interface to strglob library
.\" ----------------------------------------------------------------------------
.SH SYNOPSIS
\fBstrglob\fR [\fIOPTIONS\fR]
.\" ----------------------------------------------------------------------------
.SH DESCRIPTION
.B strglob
is a command-line application that implements essential functions of the 
string globbing library libstrglob.  It expands a glob pattern into one or more
strings; basically, it has been made to test the library's features via shell.
It constructs the string(s) that a given pattern is meant to represent.
.\" ----------------------------------------------------------------------------
.SH OPTIONS
.B glob(7) 
style pattern that represents the strings to be generated.
.\" ----------------------------------------------------------------------------
.SH HOMEPAGE
libstrglob is part of the
.UR https://github.com/decal/strglob/wiki
strglob project
.UE .
.\" ----------------------------------------------------------------------------
.SH AUTHORS
The libstrglob library, including strglob, was written by
.MT decal@sdf.org
Derek Callaway
.ME .
