#!/usr/bin/env bash

# Each one of these invocations should have a non-zero return code due to syntax error..

set -x

./strglob '[1-3'
./strglob '['
./strglob '[0'
./strglob '[01'
./strglob '[01-'
./strglob '[01-0'
./strglob '{a,b'

exit 0
