#!/usr/bin/env bash

# Each one of these invocation should have a zero return code..

set -x

./urlglob ''
./urlglob 'QQ'
./urlglob '[1-3]'
./urlglob '[1-03]'
./urlglob '[01-03]'
./urlglob '[1-3]QQ'
./urlglob '[1-3]QQ[4-5]'
./urlglob 'QQ[4-5]'
./urlglob '[1-2]QQ{4,5}'
./urlglob ' [1-2]QQ[4-5]'
./urlglob '[1-2][4-5]'
./urlglob '[1-2]{a,b,c}'
./urlglob 'Q[1-2]QQ[4-5]'
./urlglob '{a,b,c}'
./urlglob 'QQ{a,b,c}'
./urlglob '{a,b,c}QQ'
./urlglob 'QQ{a,b,c}QQ'
./urlglob '{a,b,c}{x,y,z}'
./urlglob '{a,b,c}QQ{x,y,z}'
./urlglob 'QQ{a,b,c}QQ{x,y,z}'
./urlglob '{a,b,c}QQ{x,y,z}QQ'
./urlglob 'QQ{a,b,c}QQ{x,y,z}QQ'
./urlglob '[100-200]'

exit 0
