#!/usr/bin/env bash

# Each one of these invocation should have a zero return code..

set -x

./strglob ''
./strglob 'QQ'
./strglob '[1-3]'
./strglob '[1-03]'
./strglob '[01-03]'
./strglob '[1-3]QQ'
./strglob '[1-3]QQ[4-5]'
./strglob 'QQ[4-5]'
./strglob '[1-2]QQ{4,5}'
./strglob ' [1-2]QQ[4-5]'
./strglob '[1-2][4-5]'
./strglob '[1-2]{a,b,c}'
./strglob 'Q[1-2]QQ[4-5]'
./strglob '{a,b,c}'
./strglob 'QQ{a,b,c}'
./strglob '{a,b,c}QQ'
./strglob 'QQ{a,b,c}QQ'
./strglob '{a,b,c}{x,y,z}'
./strglob '{a,b,c}QQ{x,y,z}'
./strglob 'QQ{a,b,c}QQ{x,y,z}'
./strglob '{a,b,c}QQ{x,y,z}QQ'
./strglob 'QQ{a,b,c}QQ{x,y,z}QQ'
./strglob '[100-200]'

exit 0
